# TODO нужен нормальный интерфейс создания сцен и не забыть вырезать билдер из gui

[workspace]
resolver = "2"
members = [ "builder","gui", "project_2", "renderer", "resources", "scene"]

[workspace.dependencies]
gui = { path = "./gui" }
renderer = { path = "./renderer" }
resources = { path = "./resources" }
scene = { path = "./scene" }
error-stack = "0.5.0"
thiserror = "2.0.4"
config = "0.15.4"
