[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
error-stack = "0.5.0"
log = { version = "0.4.22", features = ["std"] }
piston = "1.0.0"
thiserror = "2.0.4"
piston2d-graphics = "0.44.0"
pistoncore-glutin_window = "0.72.0"
piston2d-opengl_graphics = "0.84.0"
