[package]
name = "scene"
version = "0.1.0"
edition = "2021"

[dependencies]
builder = { workspace = true }
resources = { workspace = true }
renderer = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }
utils ={ workspace = true }
