[package]
name = "project_2"
version = "0.1.0"
edition = "2021"

[dependencies]
renderer = { workspace = true }
resources = { workspace = true }
scene = { workspace = true }
gui = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }
