name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Check fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cargo fmt --check
        run: cargo fmt --check
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cargo test
        run: cargo test
  doc:
    name: Doc tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cargo test --doc
        run: cargo test --doc
  build_ubuntu:
    name: Build (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: cargo build --release
  build_windows:
    name: Build (Windows)
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: cargo build --release
